export const adminPageLocators = {
  addUserTitle: "h6:contains('Add User')",
  userRoleLabel: 'label:contains("User Role")',
  userRoleOption: ".oxd-select-option",
  employeeNameLabel: 'label:contains("Employee Name")',
  statusLable: "label:contains('Status')",
  statusInput: 'div[class="oxd-select-text-input"]',
  statusOption: ".oxd-select-option",
  usernameInput: 'label:contains("Username")',
  passwordInput: "Password",
  confirmPasswordInput: "Confirm Password",
  systemUsersHeader: "h5:contains('System Users')",
  userTableRow: ".oxd-table-body .oxd-table-row",
  deleteSelectedButton: "button:contains('Delete Selected')",
  deleteConfirmationMessage: "p:contains('Are you Sure?')",
  deleteConfirmationButton: "button:contains('Yes, Delete')",
  orangeHrmContainer: ".orangehrm-container",
  jobTab: "span:contains('Job')",
  jobTitlesLink: "a:contains('Job Titles')",
  addJobTitle: 'h6:contains("Add Job Title")',
  jobTitleInput: 'label:contains("Job Title")',
  jobDescriptionTextarea: 'label:contains("Job Description")',
  jobNoteTextarea: 'label:contains("Note")',
  jobSpecificationLable: 'label:contains("Job Specification")',
  textFieldClass: 'div[class="oxd-select-text-input"]',
  autoCompleteTextField: ".oxd-autocomplete-wrapper",
};
