export const gatewayLocator = {
  gatewayManagementTab: "//button[span[text()='Gateway Management']]",
  gatewaysText: "div:contains('Gateways')",
  addGatewayButton: 'button[title="Add Gateway"]',
  manufacturerLabel: "label:contains('Manufacturer')",
  manufacturerOption: (manufacturer) =>
    `div.text_I6p4I:contains('${manufacturer}')`,
  gatewaySIDLabel: "label:contains('Gateway SID')",
  gatewayTypeLabel: "label:contains('Gateway Type')",
  gatewayTypeOption: (type) => `div.text_I6p4I:contains('${type}')`,
  gatewayNameLabel: "label:contains('Gateway Name')",
  locationPolicyLabel: "label:contains('Gateway/Location Policy')",
  buildingLabel: "label:contains('Building')",
  buildingOption: (building) => `span:contains('${building}')`,
  floorLabel: "label:contains('Floor')",
  floorOption: (floor) => `span:contains('${floor}')`,
  selectLocationInput: "span:contains('Select Location')",
  locationOption: (location) => `span:contains('${location}')`,
  createButton: "button[type='submit']:contains('Create')",
  successMessage: "div:contains('Gateway Created Successfully')",
  unassignButton: "button[title='Unassign']",
  unassignSuccessMessage: "div:contains('Gateway Unassigned')",
  unAssignText: "div:contains('Unassign Gateway')",
  unAssignConfirmButton: "button:contains('Unassign')",
  rowRole: 'div[role="row"]',
  deleteButton: "button[name='Delete']",
  deleteConfirmationMessage: "div:contains('Delete Gateway')",
  deleteConfirmButton: "button:contains('Delete')",
  deleteSuccessMessage: "div:contains('Gateway Deleted Successfully')",
};
