export const recruitmentPageLocators = {
  recruitmentTab: "a:contains('Recruitment')",
  firstNameInput: '[name="firstName"]',
  middleNameInput: '[name="middleName"]',
  lastNameInput: '[name="lastName"]',
  jobTitleDropdown: ".oxd-select-text-input",
  jobTitleOption: ".oxd-select-wrapper",
  roleOption: 'div[role="option"]',
  emailInput: "label:contains('Email')",
  contactNumberInput: "label:contains('Contact Number')",
  keywordsInput: "label:contains('Keywords')",
  notesTextarea: "label:contains('Notes')",
  addVacancyText: 'h6:contains("Add Vacancy")',
  vacanciesTab: "a:contains('Vacancies')",
  vacancyNameInput: "label:contains('Vacancy Name')",
  jobTitleLabel: "label:contains('Job Title')",
  jobTitleDropdownWrapper: ".oxd-select-wrapper",
  jobTitleDropdownInput: ".oxd-select-text-input",
  descriptionTextarea: "label:contains('Description')",
  hiringManagerInput: "label:contains('Hiring Manager')",
  autocompleteWrapper: ".oxd-autocomplete-wrapper",
  numberOfPositionsInput: "label:contains('Number of Positions')",
};
