export const sensor = {
  sensorManagementTab: '//button[span[text()="Sensor Management"]]',
  sensorText: 'div:contains("Sensors")',
  addSensorButton: 'button[title="Add Sensor"]',
  sensorIdField: 'input[placeholder="Enter Sensor ID"]',
  sensorTypeDropdown: 'span:contains("Select Sensor Type")',
  manufacturer: 'label:contains("Manufacturer")',
  manufacturerOption: ".text_I6p4I",
  model: 'label:contains("Model")',
  createButton: 'button[type="submit"]:contains("Create")',
  successToast: "div:contains('Sensor Created Successfully')",
  seachInput: "input[placeholder='Search']",
  searchButton: "button:contains('Search')",
  deleteButton: 'button.button-tableDeleteItem_CYB77[title="Delete"]',
  deleteSensortext: 'div:contains("Delete Sensor")',
  deleteConfirm: 'span:contains("Delete")',
  deleteToast: 'div:contains("Sensor Deleted Successfully")',
};
